### ISSUE TITLE
Return of StaticImports.xform

### ISSUE THREAD

**Issue by BrenoTrancoso** [GlenKPeterson/Paguro#14]
StaticImports: 

public static <<T>T> **Transformable<<T>T>** xform(Iterable<T> iterable);
public static <<T>T> **Transformable<<T>T>** xformArray(T... items);

To

public static <<T>T> **Xform<<T>T>** xform(Iterable<T> iterable);
public static <<T>T> **Xform<<T>T>** xformArray(T... items);

**Comment by GlenKPeterson** [comment]
Thank you for your interest!  What is the benefit of exposing the implementation instead of the interface?  What do you need from Xform that you don't get from Transformable?

**Comment by BrenoTrancoso** [comment]
xform(new ArrayList<>()).forEach(x -> {}) -> forEach doesn't exists.
Xform.of(new ArrayList<>()).forEach(x -> {}) -> forEach exists.

xform(new ArrayList<String>()).flatMap(x -> xform(new ArrayList<Integer>())) -> Type mismatch: cannot convert from Transformable<Integer> to Iterable<Object>
xform(new ArrayList<String>()).flatMap(x -> Xform.of(new ArrayList<Integer>())) -> OK

Maybe to public static <<T>T> UnmodIterable<<T>T> xform(Iterable iterable);

**Comment by GlenKPeterson** [comment]
Thank you for finding and reporting this.  I really like your suggestion to use UnmodIterable instead of Transformable and have made that change as you suggest in Paguro 2.0.16.
