### ISSUE TITLE
Concatenating RrbTree's with different element types gives ArrayStoreException

### ISSUE THREAD

**Issue by fcurts** [GlenKPeterson/Paguro#29]
... when iterating over the resulting tree.

I suspect (but haven't verified) that the culprit is RrbTree:1418 and RrbTree:1377, which choose `items[0].getClass()` as the array element type to be passed to `Array.newInstance()`. This only seems safe if the array is known to be homogeneous.

It would be great if Paguro could do without `Array.newInstance()`, as reflective array instantiation makes Paguro difficult to impossible to compile to native code with GraalVM.

Paguro 3.1.0, Oracle JDK 1.8.0_191.

Reproducer:

```
import org.junit.jupiter.api.Test;
import org.organicdesign.fp.StaticImports;
import org.organicdesign.fp.collections.RrbTree;

public class RrbTreeBug {
  @Test
  public void test() {
    RrbTree<Object> rrb =
        // first tree needs to contain at least 32 elements for the bug to surface
        StaticImports.<Object>rrb(1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10,1,2)
            .concat(StaticImports.<Object>rrb("a"));

    // iterating throws ArrayStoreException
    for (Object elem : rrb) {
      System.out.println(elem);
    }
  }
}
```

Stack trace:
```
java.lang.ArrayStoreException
	at java.lang.System.arraycopy(Native Method)
	at org.organicdesign.fp.collections.Cowry.spliceIntoArrayAt(Cowry.java:126)
	at org.organicdesign.fp.collections.RrbTree$Leaf.pushFocus(RrbTree.java:1417)
	at org.organicdesign.fp.collections.RrbTree$ImRrbt.pushFocus(RrbTree.java:693)
	at org.organicdesign.fp.collections.RrbTree$ImRrbt.iterator(RrbTree.java:686)
	at RrbTreeBug.test(RrbTreeBug.java:13)
```

**Comment by GlenKPeterson** [comment]
The ArrayStoreException is fixed in 3.1.1 which should be available shortly (it's slowly releasing to Maven Central as I type this).

Thank you for your excellent bug report - with unit test!  I had wondered if there was a bug like this, but didn't exactly know what to look for.

Please open a separate bug for Array.newInstance().  That's going to be more difficult to remove as it complicates the types.  I could work on that this weekend and maybe release a branch for you to try out.  If that works, I'll consider merging it into the main branch if it all looks reasonable.

**Comment by GlenKPeterson** [comment]
Ugh.  The maven deploy timed out and I forgot to push to GitHub before deploying.  I also made a 3.1.1 version without your change, minutes earlier, so if you pulled already, you didn't get my changes.  Please pull from GitHub now and try it out.  I'll figure out the Sonatype (Maven Central) timeout later, maybe this weekend.

**Comment by fcurts** [comment]
Thanks for the quick fix! Looking forward to the Maven Central release. Will file a separate issue for `Array.newInstance()`.

**Comment by GlenKPeterson** [comment]
Oh.  I've messed up my version numbers - Oops!  There's already a 3.1.1 release in the Kotlin foot-wetting branch.  I think I need to make those releases 3.5.x and then make a 3.1.2 release for your change.  Again, that's for the weekend.

**Comment by GlenKPeterson** [comment]
This is fixed.  There's a 3.1.2 sent to Maven Central with this change.  The other branch has been renamed to Paguro-KF (for Kotlin-Friendly) and had its version number bumped to 3.5.x to avoid repeat issues.  Thanks again for your very clear bug report and excellent test (which, slightly modified, is now part of this project).
