### ISSUE TITLE
get fails for some indexes after joining two RrbTree vectors of certain sizes

### ISSUE THREAD

**Issue by jafingerhut** [GlenKPeterson/Paguro#36]
New failing test cases given in this PR: https://github.com/GlenKPeterson/Paguro/pull/35

I don't have a more full analysis or proposed fix yet, but may spend some time looking for one.

**Comment by GlenKPeterson** [comment]
I think this is fixed.  I'm closing this, but we can track similar issues on #35 if necessary.
