### ISSUE TITLE
Support Request: Creating a PersistentVector 

### ISSUE THREAD

**Issue by smillies** [GlenKPeterson/Paguro#38]
Hi there,

I was wondering what would be the most concise and efficient way to create a PersistentVector from a single element?
Is it
`PersistentVector.ofIter(Collections.singletonList(elem));`
or
`PersistentVector.empty().append(elem)`
or is there some simpler way? 

I was looking for a factory method with a varargs signature, so that something like
`PersistentVector.of(elem1, elem2, elem3)`
becomes possible.

I apologize if opening an issue is not the right way to ask for support.
Best regards,
Sebastian

**Comment by GlenKPeterson** [comment]
import org.organicdesign.fp.StaticImports;

vec(elem)

Thanks for your interest!
