### ISSUE TITLE
ImList, MutList - example for best practice of inserting an element before an existing element

### ISSUE THREAD

**Issue by axkr** [GlenKPeterson/Paguro#45]
Is there an example for best practice of inserting an element before an existing element in ImList, MutList?

Do I have to 
- copy all elements below the "insert point" into a new mutList
- insert the new element at "insert point" in the mutList
- copy all elements greater equal the "insert point" into the mutList
- call mutList.immutable() at the end

**Comment by GlenKPeterson** [comment]
Sorry I couldn't get back to you sooner - on vacation.  Clojure's PersistentVector is different from Java's ArrayList in that it does not support random insertion (in other ways as well).  However, the RRB-Tree in Paguro (and a different one in Clojure) does.  RrbTree in this project has .insertAt(T, int) that should do what you need.  The way your question is worded may also require .indexOf(Object).

**Comment by GlenKPeterson** [comment]
Another option (off the top of my head) is to use Paguro's transforms, but this is at least O(n) (RRB-Tree is O(log n):

```
myVec.take(idx)
     .append(myItem)
     .concat(myVec.drop(idx))
     .toImList()
```

That should work with mutable or immutable.

**Comment by axkr** [comment]
Ok I'm using RRB-Tree now and that seems to work.

I opened this issue to track it in my project:
- https://github.com/axkr/symja_android_library/issues/334
